thesis:
	latexmk -pdf presentation.tex
latex:
	latexmk -pdf presentation.tex

xdvi:
	xdvi -background white presentation.dvi -s 5 -sidemargin 0.0cm -topmargin 1.0cm -hush -expertmode 0 -geometry 750x987+0+0 >& /dev/null &

