thesis:
	latexmk -pdf thesis.tex
latex:
	latexmk -pdf thesis.tex

xdvi:
	xdvi -background white thesis.dvi -s 5 -sidemargin 0.0cm -topmargin 1.0cm -hush -expertmode 0 -geometry 750x987+0+0 >& /dev/null &

